parameters:
#    agi_user.example.class: Demierre\UserBundle\Example

services:
    agi_user.registration.form.type:
            class: Demierre\UserBundle\Form\Type\RegistrationFormType
            arguments: [%fos_user.model.user.class%]
            tags:
                - { name: form.type, alias: agi_user_registration } 
    agi_user.profile.form.type:
            class: Demierre\UserBundle\Form\Type\ProfileFormType
            arguments: [%fos_user.model.user.class%]
            tags:
                - { name: form.type, alias: agi_user_profile } 
    login_listener:
        class: 'Demierre\UserBundle\EventListener\LoginListener'
        arguments: ['@security.context', '@router', '@doctrine', '@event_dispatcher']
        tags:
            - { name: 'kernel.event_listener', event: 'security.interactive_login', method: onSecurityInteractiveLogin }
    